all_joints:
- [0]
- [1]
- [2]
- [3]
- [4]
- [5]
- [6]
- [7]
- [8]
- [9]
- [10]
- [11]
- [12]
- [13]
all_joints_names: [snout, left_ear, right_ear, spine1, spine2, tail1, tail2, tail3,
  food_port, ll_corner, lr_corner, l_screen, m_screen, r_screen]
alpha_r: 0.02
apply_prob: 0.8
batch_size: 8
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size: [400, 400]
cropratio: 0.4
dataset: training-datasets/iteration-5/UnaugmentedDataSet_BanditMar1/Bandit_Harris95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
edge: false
emboss:
  alpha: [0.0, 1.0]
  embossratio: 0.1
  strength: [0.5, 1.5]
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: ./snapshot-30000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 1.0e-05
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-5/UnaugmentedDataSet_BanditMar1/Documentation_data-Bandit_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- [3.0e-05, 7500]
- [1.0e-05, 12000]
- [5.0e-06, 200000]
net_type: resnet_50
num_idchannel: 0
num_joints: 14
num_limbs: 28
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- [0, 1]
- [0, 2]
- [0, 3]
- [0, 4]
- [0, 5]
- [0, 6]
- [0, 7]
- [1, 2]
- [1, 3]
- [1, 4]
- [1, 5]
- [1, 6]
- [1, 7]
- [2, 3]
- [2, 4]
- [2, 5]
- [2, 6]
- [2, 7]
- [3, 4]
- [3, 5]
- [3, 6]
- [3, 7]
- [4, 5]
- [4, 6]
- [4, 7]
- [5, 6]
- [5, 7]
- [6, 7]
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /content/drive/MyDrive/DLC/Bandit-Harris-2022-03-01
rotation: 80
rotratio: 0.6
save_iters: 1000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: true
sharpenratio: 0.3
weigh_only_present_joints: false
